### ISSUE TITLE
Feature Request: Add intentions

### ISSUE THREAD

**Issue by thesurlydev** [jeshan/typeformation#3]
Intentions would be helpful in addition to the live templates. For example, when a !Ref doesn't resolve add intention to optionally add a parameter in the template.

**Comment by jeshan** [comment]
For such features, I personally use and recommend the existing [AWS Cloudformation](https://plugins.jetbrains.com/plugin/7371-aws-cloudformation) plugin.

![image](https://user-images.githubusercontent.com/1020565/41990270-f974bc5a-7a52-11e8-8d09-db525b350826.png)

I'll keep this one focused on live templates mostly.

**Comment by jeshan** [comment]
It doesn't specifically add the intention you suggested but there's an [open request](https://github.com/shalupov/idea-cloudformation/issues/62) for it.
